package com.suchenghe;

import java.util.Date;

public class CarSales {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.trace_id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String traceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.data_source
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String dataSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.vin
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String vin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.series_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String seriesCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.model_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String modelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.mat_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String matCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.color_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.factory_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String factoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.engine_no
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String engineNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.dealer_id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String dealerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.model_code_as
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private String modelCodeAs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.gmt_create
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_access_car_sales.gmt_modified
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.id
     *
     * @return the value of data_access_car_sales.id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.id
     *
     * @param id the value for data_access_car_sales.id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.trace_id
     *
     * @return the value of data_access_car_sales.trace_id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.trace_id
     *
     * @param traceId the value for data_access_car_sales.trace_id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId == null ? null : traceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.data_source
     *
     * @return the value of data_access_car_sales.data_source
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.data_source
     *
     * @param dataSource the value for data_access_car_sales.data_source
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.vin
     *
     * @return the value of data_access_car_sales.vin
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.vin
     *
     * @param vin the value for data_access_car_sales.vin
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.series_code
     *
     * @return the value of data_access_car_sales.series_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getSeriesCode() {
        return seriesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.series_code
     *
     * @param seriesCode the value for data_access_car_sales.series_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setSeriesCode(String seriesCode) {
        this.seriesCode = seriesCode == null ? null : seriesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.model_code
     *
     * @return the value of data_access_car_sales.model_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.model_code
     *
     * @param modelCode the value for data_access_car_sales.model_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode == null ? null : modelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.mat_code
     *
     * @return the value of data_access_car_sales.mat_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getMatCode() {
        return matCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.mat_code
     *
     * @param matCode the value for data_access_car_sales.mat_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setMatCode(String matCode) {
        this.matCode = matCode == null ? null : matCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.color_code
     *
     * @return the value of data_access_car_sales.color_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getColorCode() {
        return colorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.color_code
     *
     * @param colorCode the value for data_access_car_sales.color_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setColorCode(String colorCode) {
        this.colorCode = colorCode == null ? null : colorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.factory_code
     *
     * @return the value of data_access_car_sales.factory_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.factory_code
     *
     * @param factoryCode the value for data_access_car_sales.factory_code
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode == null ? null : factoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.engine_no
     *
     * @return the value of data_access_car_sales.engine_no
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.engine_no
     *
     * @param engineNo the value for data_access_car_sales.engine_no
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo == null ? null : engineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.dealer_id
     *
     * @return the value of data_access_car_sales.dealer_id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.dealer_id
     *
     * @param dealerId the value for data_access_car_sales.dealer_id
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setDealerId(String dealerId) {
        this.dealerId = dealerId == null ? null : dealerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.model_code_as
     *
     * @return the value of data_access_car_sales.model_code_as
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public String getModelCodeAs() {
        return modelCodeAs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.model_code_as
     *
     * @param modelCodeAs the value for data_access_car_sales.model_code_as
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setModelCodeAs(String modelCodeAs) {
        this.modelCodeAs = modelCodeAs == null ? null : modelCodeAs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.gmt_create
     *
     * @return the value of data_access_car_sales.gmt_create
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.gmt_create
     *
     * @param gmtCreate the value for data_access_car_sales.gmt_create
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_access_car_sales.gmt_modified
     *
     * @return the value of data_access_car_sales.gmt_modified
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_access_car_sales.gmt_modified
     *
     * @param gmtModified the value for data_access_car_sales.gmt_modified
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}