package com.suchenghe;

import com.suchenghe.CarSales;
import com.suchenghe.CarSalesExample;
import org.apache.ibatis.annotations.Param;

public interface CarSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_access_car_sales
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    int insert(CarSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_access_car_sales
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    int insertSelective(CarSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_access_car_sales
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") CarSales record, @Param("example") CarSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_access_car_sales
     *
     * @mbg.generated Thu Jun 20 16:06:58 CST 2019
     */
    int updateByExample(@Param("record") CarSales record, @Param("example") CarSalesExample example);
}